name: Playwright API Automation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout kode
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3. Install dependencies
    - name: Install dependencies
      run: npm install

    # 4. Jalankan Playwright tests
    - name: Run Playwright API tests
      run: npm test

    # 5. Start Allure Docker Service
    - name: Start Allure Docker Service
      run: docker-compose up -d allure

    # 6. Copy Allure results ke Docker
    - name: Copy Allure Results to Docker
      run: docker cp allure-results allure-docker-service:/app/allure-results

    # 7. Generate Allure report
    - name: Generate Allure Report
      run: docker exec allure-docker-service allure generate --clean

    # 8. Publish Allure Report URL
    - name: Publish Allure Report URL
      run: "echo 'Allure Report URL: http://localhost:5050'"

    # 9. Stop Allure Docker Service (Optional Cleanup)
    - name: Stop Allure Docker Service
      run: docker-compose down
